### ISSUE TITLE
Loading packages for initial movies app is tripping me up

### ISSUE THREAD

**Issue by esimms999** [mjfrigaard/shiny-app-pkgs#2]
When I select Run App, I get this pop-up:

![20230912_01](https://github.com/mjfrigaard/shinyap/assets/10915780/1bf1ec74-1166-4357-990c-471e398f3210)

If I select "Yes":

![20230912_02](https://github.com/mjfrigaard/shinyap/assets/10915780/608bd374-cadd-4ae6-9627-f5dc924876a8)

If I try again and select "No":

![20230912_03](https://github.com/mjfrigaard/shinyap/assets/10915780/0b73e60b-c756-4728-bbb5-1abddd258e9b)

**Comment by mjfrigaard** [comment]
Install the package first (following the advice at the top of the script). 
<img width="859" alt="image" src="https://github.com/mjfrigaard/shinyap/assets/8368326/89fca163-59d1-45dd-b37c-d7dff89b4929">

**Comment by esimms999** [comment]
Very confusing. The first thing this code will do is install.packages, including shinythemes. Which is why I was ignoring the message you are saying to follow. Is there a way to make this just work? Otherwise, there will need to be info about following that message if it pops up.

**Comment by mjfrigaard** [comment]
This works fine in Posit.Cloud when I open `app.R`, run the initial install, then comment out and click **Run App**.

<img width="1539" alt="image" src="https://github.com/mjfrigaard/shinyap/assets/8368326/c4b486f2-ee07-4f9a-b921-382a62193021">

Not sure what the issue is on your machine, but I will make the steps more explicit.

**Comment by mjfrigaard** [comment]
I don't know how to make this any clearer: 
<img width="737" alt="image" src="https://github.com/mjfrigaard/shinyap/assets/8368326/50833675-7650-46ce-b042-6c5a37fa420d">
